#!/usr/bin/env python3
"""Generate the checked-in fixed-size FFT twiddle tables."""

import math
import struct


def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def literal(value):
    # Preserve the exact binary32 value used by the encoder.
    return f32(value).hex() + "f"


print("/* Generated by tools/gen_fft_twiddles.py; do not edit. */")
print()

for span in (16, 64, 256, 1024):
    kx = span // 8

    print(f"static const dht_twiddle_t dht_tw{span}[{kx - 1}] = {{")

    for i in range(1, kx):
        theta = 2.0 * math.pi * i / span
        print(
            "    { %s, %s, %s, %s },"
            % (
                literal(math.cos(theta)),
                literal(math.sin(theta)),
                literal(math.cos(2.0 * theta)),
                literal(math.sin(2.0 * theta)),
            )
        )

    print("};")
    print()
